-- MySQL Script generated by MySQL Workbench
-- Thu Apr 16 10:44:01 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ABET
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ABET
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ABET` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ABET` ;

-- -----------------------------------------------------
-- Table `ABET`.`ACADEMIC_TERM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ABET`.`ACADEMIC_TERM` ;

CREATE TABLE IF NOT EXISTS `ABET`.`ACADEMIC_TERM` (
  `term_ID` INT NOT NULL AUTO_INCREMENT,
  `term_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`term_ID`),
  UNIQUE INDEX `term_name` (`term_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ABET`.`USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ABET`.`USER` ;

CREATE TABLE IF NOT EXISTS `ABET`.`USER` (
  `user_ID` INT NOT NULL AUTO_INCREMENT,
  `inter_ID` VARCHAR(255) NULL DEFAULT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `phone_number` VARCHAR(255) NOT NULL,
  `date_created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_ID`),
  UNIQUE INDEX `inter_ID` (`inter_ID` ASC) VISIBLE,
  UNIQUE INDEX `inter_ID_2` (`inter_ID` ASC, `email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ABET`.`COURSE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ABET`.`COURSE` ;

CREATE TABLE IF NOT EXISTS `ABET`.`COURSE` (
  `course_ID` INT NOT NULL AUTO_INCREMENT,
  `course_name` VARCHAR(255) NOT NULL,
  `course_number` VARCHAR(255) NOT NULL,
  `course_description` TEXT CHARACTER SET 'latin1' NOT NULL,
  `date_created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`course_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 68
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ABET`.`STUDENT_OUTCOME`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ABET`.`STUDENT_OUTCOME` ;

CREATE TABLE IF NOT EXISTS `ABET`.`STUDENT_OUTCOME` (
  `outc_ID` INT NOT NULL AUTO_INCREMENT,
  `outc_name` VARCHAR(255) NOT NULL,
  `outc_description` TEXT CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `date_created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `prog_ID` INT NOT NULL,
  PRIMARY KEY (`outc_ID`),
  UNIQUE INDEX `outc_name` (`outc_name` ASC, `prog_ID` ASC) VISIBLE,
  INDEX `prog_ID` (`prog_ID` ASC) VISIBLE,
  CONSTRAINT `STUDENT_OUTCOME_ibfk_1`
    FOREIGN KEY (`prog_ID`)
    REFERENCES `ABET`.`study_program` (`prog_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ABET`.`PERF_CRITERIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ABET`.`PERF_CRITERIA` ;

CREATE TABLE IF NOT EXISTS `ABET`.`PERF_CRITERIA` (
  `perC_ID` INT NOT NULL AUTO_INCREMENT,
  `perC_Desk` VARCHAR(450) CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `perC_order` INT NULL DEFAULT NULL,
  `outc_ID` INT NOT NULL,
  PRIMARY KEY (`perC_ID`),
  INDEX `PERF_CRITERIA_ibfk_1_idx` (`outc_ID` ASC) VISIBLE,
  CONSTRAINT `PERF_CRITERIA_ibfk_1`
    FOREIGN KEY (`outc_ID`)
    REFERENCES `ABET`.`STUDENT_OUTCOME` (`outc_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 105
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ABET`.`EVALUATION_RUBRIC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ABET`.`EVALUATION_RUBRIC` ;

CREATE TABLE IF NOT EXISTS `ABET`.`EVALUATION_RUBRIC` (
  `rubric_ID` INT NOT NULL AUTO_INCREMENT,
  `rubric_name` VARCHAR(255) NOT NULL,
  `rubric_description` TEXT CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `outc_ID` INT NOT NULL,
  `isFinal` TINYINT(1) NOT NULL DEFAULT '0',
  `date_created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `date_modified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`rubric_ID`),
  INDEX `EVALUATION_RUBRIC_ibfk_1_idx` (`outc_ID` ASC) VISIBLE,
  CONSTRAINT `EVALUATION_RUBRIC_ibfk_1`
    FOREIGN KEY (`outc_ID`)
    REFERENCES `ABET`.`STUDENT_OUTCOME` (`outc_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 41
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ABET`.`PERFORMANCE_RUBRIC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ABET`.`PERFORMANCE_RUBRIC` ;

CREATE TABLE IF NOT EXISTS `ABET`.`PERFORMANCE_RUBRIC` (
  `rubric_ID` INT NOT NULL AUTO_INCREMENT,
  `perC_ID` INT NOT NULL,
  PRIMARY KEY (`rubric_ID`, `perC_ID`),
  INDEX `PERFORMANCE_RUBRIC_ibfk_1_idx` (`perC_ID` ASC) VISIBLE,
  CONSTRAINT `PERFORMANCE_RUBRIC_ibfk_1`
    FOREIGN KEY (`perC_ID`)
    REFERENCES `ABET`.`PERF_CRITERIA` (`perC_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Performance_Rubric_rubric_id`
    FOREIGN KEY (`rubric_ID`)
    REFERENCES `ABET`.`EVALUATION_RUBRIC` (`rubric_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 41
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ABET`.`ASSESSMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ABET`.`ASSESSMENT` ;

CREATE TABLE IF NOT EXISTS `ABET`.`ASSESSMENT` (
  `assessment_ID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `course_ID` INT NOT NULL,
  `term_ID` INT NOT NULL,
  `user_ID` INT NOT NULL,
  `rubric_ID` INT NOT NULL,
  `course_section` INT NULL DEFAULT NULL,
  `creation_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` VARCHAR(20) NULL DEFAULT 'in_progress',
  PRIMARY KEY (`assessment_ID`),
  INDEX `course_ID` (`course_ID` ASC) VISIBLE,
  INDEX `ASSESSMENT_ibfk_4` (`term_ID` ASC) VISIBLE,
  INDEX `ASSESSMENT_ibfk_1_idx` (`user_ID` ASC) VISIBLE,
  INDEX `ASSESSMENT_ibfk_3_idx` (`rubric_ID` ASC) VISIBLE,
  CONSTRAINT `ASSESSMENT_ibfk_1`
    FOREIGN KEY (`user_ID`)
    REFERENCES `ABET`.`USER` (`user_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ASSESSMENT_ibfk_2`
    FOREIGN KEY (`course_ID`)
    REFERENCES `ABET`.`COURSE` (`course_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ASSESSMENT_ibfk_3`
    FOREIGN KEY (`rubric_ID`)
    REFERENCES `ABET`.`PERFORMANCE_RUBRIC` (`rubric_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ASSESSMENT_ibfk_4`
    FOREIGN KEY (`term_ID`)
    REFERENCES `ABET`.`ACADEMIC_TERM` (`term_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 183
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ABET`.`ASSESSMENT_GRAPH`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ABET`.`ASSESSMENT_GRAPH` ;

CREATE TABLE IF NOT EXISTS `ABET`.`ASSESSMENT_GRAPH` (
  `graph_ID` INT NOT NULL AUTO_INCREMENT,
  `assessment_ID` INT NOT NULL,
  `base_64` TEXT NOT NULL,
  PRIMARY KEY (`graph_ID`, `assessment_ID`),
  UNIQUE INDEX `no_duplicates` (`assessment_ID` ASC) VISIBLE,
  CONSTRAINT `assessment_graph_ibfk_1`
    FOREIGN KEY (`assessment_ID`)
    REFERENCES `ABET`.`ASSESSMENT` (`assessment_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ABET`.`DEPARTMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ABET`.`DEPARTMENT` ;

CREATE TABLE IF NOT EXISTS `ABET`.`DEPARTMENT` (
  `dep_ID` INT NOT NULL AUTO_INCREMENT,
  `dep_name` VARCHAR(255) NOT NULL,
  `dep_description` TEXT CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `date_created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`dep_ID`),
  UNIQUE INDEX `dep_name` (`dep_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ABET`.`EVALUATION_ROW`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ABET`.`EVALUATION_ROW` ;

CREATE TABLE IF NOT EXISTS `ABET`.`EVALUATION_ROW` (
  `row_ID` INT NOT NULL AUTO_INCREMENT,
  `assessment_ID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`row_ID`),
  INDEX `fk_onCascade_onUpdate` (`assessment_ID` ASC) VISIBLE,
  CONSTRAINT `EVALUATION_ROW_ibfk_1`
    FOREIGN KEY (`assessment_ID`)
    REFERENCES `ABET`.`ASSESSMENT` (`assessment_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_onCascade_onUpdate`
    FOREIGN KEY (`assessment_ID`)
    REFERENCES `ABET`.`ASSESSMENT` (`assessment_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1423
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ABET`.`OUTCOME_COURSE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ABET`.`OUTCOME_COURSE` ;

CREATE TABLE IF NOT EXISTS `ABET`.`OUTCOME_COURSE` (
  `course_ID` INT NOT NULL,
  `outc_ID` INT NOT NULL,
  UNIQUE INDEX `course_ID_3` (`course_ID` ASC, `outc_ID` ASC) VISIBLE,
  UNIQUE INDEX `course_ID_4` (`course_ID` ASC, `outc_ID` ASC) VISIBLE,
  UNIQUE INDEX `course_ID_5` (`course_ID` ASC, `outc_ID` ASC) VISIBLE,
  INDEX `course_ID` (`course_ID` ASC) VISIBLE,
  INDEX `OUTCOME_COURSE_ibfk_1_idx` (`outc_ID` ASC) VISIBLE,
  CONSTRAINT `OUTCOME_COURSE_ibfk_1`
    FOREIGN KEY (`outc_ID`)
    REFERENCES `ABET`.`STUDENT_OUTCOME` (`outc_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `OUTCOME_COURSE_ibfk_2`
    FOREIGN KEY (`course_ID`)
    REFERENCES `ABET`.`COURSE` (`course_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ABET`.`PROFILE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ABET`.`PROFILE` ;

CREATE TABLE IF NOT EXISTS `ABET`.`PROFILE` (
  `profile_ID` INT NOT NULL AUTO_INCREMENT,
  `profile_Name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`profile_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ABET`.`STUDY_PROGRAM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ABET`.`STUDY_PROGRAM` ;

CREATE TABLE IF NOT EXISTS `ABET`.`STUDY_PROGRAM` (
  `prog_ID` INT NOT NULL AUTO_INCREMENT,
  `prog_name` VARCHAR(255) NOT NULL,
  `date_created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `dep_ID` INT NOT NULL,
  PRIMARY KEY (`prog_ID`),
  UNIQUE INDEX `prog_name` (`prog_name` ASC) VISIBLE,
  INDEX `STUDY_PROGRAM_ibfk_1_idx` (`dep_ID` ASC) VISIBLE,
  CONSTRAINT `STUDY_PROGRAM_ibfk_1`
    FOREIGN KEY (`dep_ID`)
    REFERENCES `ABET`.`DEPARTMENT` (`dep_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 57
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ABET`.`PROG_COURSE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ABET`.`PROG_COURSE` ;

CREATE TABLE IF NOT EXISTS `ABET`.`PROG_COURSE` (
  `course_ID` INT NOT NULL,
  `prog_ID` INT NOT NULL,
  INDEX `course_ID` (`course_ID` ASC) VISIBLE,
  INDEX `PROG_COURSE_ibfk_2_idx` (`prog_ID` ASC) VISIBLE,
  CONSTRAINT `PROG_COURSE_ibfk_1`
    FOREIGN KEY (`course_ID`)
    REFERENCES `ABET`.`COURSE` (`course_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `PROG_COURSE_ibfk_2`
    FOREIGN KEY (`prog_ID`)
    REFERENCES `ABET`.`STUDY_PROGRAM` (`prog_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ABET`.`REPORTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ABET`.`REPORTS` ;

CREATE TABLE IF NOT EXISTS `ABET`.`REPORTS` (
  `report_ID` INT NOT NULL AUTO_INCREMENT,
  `grade_A` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `grade_B` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `grade_C` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `grade_D` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `grade_F` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `UW` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `course_results` TEXT CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `course_reflection` TEXT CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `course_actions` TEXT CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `course_modification` TEXT NULL DEFAULT NULL,
  `result_outcome` TEXT NULL DEFAULT NULL,
  `assessment_ID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`report_ID`),
  INDEX `REPORTS_ibfk_1_idx` (`assessment_ID` ASC) VISIBLE,
  CONSTRAINT `REPORTS_ibfk_1`
    FOREIGN KEY (`assessment_ID`)
    REFERENCES `ABET`.`ASSESSMENT` (`assessment_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 132
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ABET`.`ROW_PERC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ABET`.`ROW_PERC` ;

CREATE TABLE IF NOT EXISTS `ABET`.`ROW_PERC` (
  `row_ID` INT NOT NULL,
  `perC_ID` INT NOT NULL,
  `row_perc_score` INT NULL DEFAULT NULL,
  PRIMARY KEY (`row_ID`, `perC_ID`),
  INDEX `ROW_PERC_ibfk_1` (`perC_ID` ASC) VISIBLE,
  CONSTRAINT `row_id_fk`
    FOREIGN KEY (`row_ID`)
    REFERENCES `ABET`.`EVALUATION_ROW` (`row_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ROW_PERC_ibfk_1`
    FOREIGN KEY (`perC_ID`)
    REFERENCES `ABET`.`PERF_CRITERIA` (`perC_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ROW_PERC_ibfk_2`
    FOREIGN KEY (`row_ID`)
    REFERENCES `ABET`.`EVALUATION_ROW` (`row_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ABET`.`USER_PROFILES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ABET`.`USER_PROFILES` ;

CREATE TABLE IF NOT EXISTS `ABET`.`USER_PROFILES` (
  `user_ID` INT NULL DEFAULT NULL,
  `profile_ID` INT NULL DEFAULT NULL,
  INDEX `USER_PROFILES_ibfk_1_idx` (`user_ID` ASC) VISIBLE,
  INDEX `USER_PROFILES_ibfk_2_idx` (`profile_ID` ASC) VISIBLE,
  CONSTRAINT `USER_PROFILES_ibfk_1`
    FOREIGN KEY (`user_ID`)
    REFERENCES `ABET`.`USER` (`user_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `USER_PROFILES_ibfk_2`
    FOREIGN KEY (`profile_ID`)
    REFERENCES `ABET`.`PROFILE` (`profile_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ABET`.`USER_STUDY_PROGRAM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ABET`.`USER_STUDY_PROGRAM` ;

CREATE TABLE IF NOT EXISTS `ABET`.`USER_STUDY_PROGRAM` (
  `user_ID` INT NULL DEFAULT NULL,
  `prog_ID` INT NULL DEFAULT NULL,
  `is_coordinator` TINYINT(1) NULL DEFAULT NULL,
  INDEX `user_ID` (`user_ID` ASC) VISIBLE,
  INDEX `prog_ID` (`prog_ID` ASC) VISIBLE,
  CONSTRAINT `user_study_program_ibfk_1`
    FOREIGN KEY (`user_ID`)
    REFERENCES `ABET`.`USER` (`user_ID`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `user_study_program_ibfk_2`
    FOREIGN KEY (`prog_ID`)
    REFERENCES `ABET`.`STUDY_PROGRAM` (`prog_ID`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ABET`.`custom_sessions_table_name`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ABET`.`custom_sessions_table_name` ;

CREATE TABLE IF NOT EXISTS `ABET`.`custom_sessions_table_name` (
  `custom_session_id` VARCHAR(128) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `custom_expires_column_name` INT UNSIGNED NOT NULL,
  `custom_data_column_name` MEDIUMTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`custom_session_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
